/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systeminv;

import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author home
 */

public class dashboard extends javax.swing.JFrame {
int globalbalance;
int globallimit;
String globalnam;
String sessionid;
int guserno;
int hold;
    /**
     * Creates new form dashboard
     */
    public dashboard() {
      
         try {
               initComponents();
          String x = login.nam.getText();
        sessionid = x;
            database db = new database();
            Statement stmt = db.getconnect();
             String querys = "SELECT * FROM `users` WHERE user_id = '"+x+"'"; 
            ResultSet rs = stmt.executeQuery(querys);
    
            while (rs.next()) {
                String name =  rs.getString("Full_Name");
                globalnam = name;
                int userno = rs.getInt("user_no");
                guserno = userno;
               int balance = rs.getInt("Balance");
               int limits = rs.getInt("acc_limit");
               int limited = rs.getInt("hold");
               hold = limited;
               
               String limitstring = String.valueOf(limits);
               limit.setText("Limit:"+limitstring);
               greatings.setText("Hi Mr/Ms:"+name);
               balances.setText("Balance:"+balance);
                 globalbalance =balance;
                    globallimit =limits;
                    if(hold == 1){
                              Component frame = null;
                      JOptionPane.showMessageDialog(frame,
    "Your Account reach the limit \n for further assistance please visit our nearest bank, we temporary hold your funds to avoid any fraudelent activity",
    "Limit Reach",
    JOptionPane.WARNING_MESSAGE);
                        errs.setText("Your have reach the limit of your account");
                    jButton2.setEnabled(false);
                    jButton1.setEnabled(false);
                    }
             } 
    
             
        } catch (SQLException ex) {
            System.out.println("error: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        greatings = new javax.swing.JLabel();
        balances = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        limit = new javax.swing.JLabel();
        errs = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setText("Dashboard");

        greatings.setText("Hi Mr John Doe");

        balances.setText("Balance:");

        jLabel2.setText("Logout");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        limit.setText("Limit:");

        jButton1.setText("Deposit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Widthdraw");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(limit, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(greatings, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(balances, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(errs, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jButton2)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(greatings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balances)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errs, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
  
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
   
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try {
            String dep = JOptionPane.showInputDialog(null,
                "Please Enter the ammount that you would like to widraw","Enter Denomination",
                JOptionPane.INFORMATION_MESSAGE);
            int widthdraw = Integer.parseInt(dep);
            if(widthdraw>globalbalance){

                Component frame = null;
                JOptionPane.showMessageDialog(frame,
                    "You dont have that much money ",
                    "insuficient funds",
                    JOptionPane.WARNING_MESSAGE);

            }else{
                database database = new database();
                Statement stmt = database.getconnect();
                int total = globalbalance - widthdraw;
                String query = "UPDATE users SET Balance ='"+total+"' WHERE user_id ='"+sessionid+"'";
                balances.setText("Balance:"+total);
                globalbalance = total;
                stmt.execute(query);
                  String log = globalnam+" Widtdraw "+dep;
                  String querys = "insert into logs(`message`, `user_no` )"
                    + " values('"+log+"', '"+guserno+"')"; 
                  stmt.execute(querys);
            }
        } catch (SQLException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             int bal = globalbalance;
        try {
                  
            String deps = JOptionPane.showInputDialog(null,
                "Please Enter the ammount that you would like to deposit","Enter Denomination",
                JOptionPane.INFORMATION_MESSAGE);
            int deposit = Integer.parseInt(deps);
             int total = globalbalance + deposit;
          if(bal >= globallimit && bal == globallimit){
                                               JOptionPane.showMessageDialog(null,
    "Your Account reach the limit \n for further assistance please visit our nearest bank, we temporary hold your funds to avoid any fraudelent activity",
    "Limit Reach",
    JOptionPane.WARNING_MESSAGE);
                        errs.setText("Your have reach the limit of your account");
                jButton1.setEnabled(false);
                jButton2.setEnabled(false);
                    database database = new database();
                Statement stmt = database.getconnect();
                      String query = "UPDATE users SET Balance ='"+total+"', hold='"+1+"' WHERE user_id ='"+sessionid+"'";
                stmt.execute(query);
                balances.setText("Balance:"+total);
                globalbalance = total;
                 bal = total;
                   String log = globalnam+" Deposited "+deps;
                  String querys = "insert into logs(`message`, `user_no` )"
                    + " values('"+log+"', '"+guserno+"')"; 
                  stmt.execute(querys);
                
            }else{
              if(deposit>=globallimit){
                   JOptionPane.showMessageDialog(null,
    "Your Account reach the limit \n for further assistance please visit our nearest bank, we temporary hold your funds to avoid any fraudelent activity",
    "Limit Reach",
    JOptionPane.WARNING_MESSAGE);
                        errs.setText("Your have reach the limit of your account");
                jButton1.setEnabled(false);
                jButton2.setEnabled(false);
                    database database = new database();
                Statement stmt = database.getconnect();
                      String query = "UPDATE users SET Balance ='"+total+"', hold='"+1+"' WHERE user_id ='"+sessionid+"'";
                stmt.execute(query);
                balances.setText("Balance:"+total);
                globalbalance = total;
                 bal = total;
  
                    String log = globalnam+" Deposited "+deps;
                  String querys = "insert into logs(`message`, `user_no` )"
                    + " values('"+log+"', '"+guserno+"')"; 
                  stmt.execute(querys);
              }
              if(bal == globallimit){
                   JOptionPane.showMessageDialog(null,
    "Your Account reach the limit \n for further assistance please visit our nearest bank, we temporary hold your funds to avoid any fraudelent activity",
    "Limit Reach",
    JOptionPane.WARNING_MESSAGE);
                        errs.setText("Your have reach the limit of your account");
                jButton1.setEnabled(false);
                jButton2.setEnabled(false);
                    database database = new database();
                Statement stmt = database.getconnect();
                      String query = "UPDATE users SET Balance ='"+total+"', hold='"+1+"' WHERE user_id ='"+sessionid+"'";
                stmt.execute(query);
                balances.setText("Balance:"+total);
                globalbalance = total;
                 bal = total;
                   String log = globalnam+" Deposited "+deps;
                  String querys = "insert into logs(`message`, `user_no` )"
                    + " values('"+log+"', '"+guserno+"')"; 
                  stmt.execute(querys);
                  
              }
               if(bal >= globallimit){
                                               JOptionPane.showMessageDialog(null,
    "Your Account reach the limit \n for further assistance please visit our nearest bank, we temporary hold your funds to avoid any fraudelent activity",
    "Limit Reach",
    JOptionPane.WARNING_MESSAGE);
                        errs.setText("Your have reach the limit of your account");
                jButton1.setEnabled(false);
                jButton2.setEnabled(false);
                    database database = new database();
                Statement stmt = database.getconnect();
                      String query = "UPDATE users SET Balance ='"+total+"', hold='"+1+"' WHERE user_id ='"+sessionid+"'";
                stmt.execute(query);
                balances.setText("Balance:"+total);
                globalbalance = total;
                 bal = total;
                   String log = globalnam+" Deposited "+deps;
                  String querys = "insert into logs(`message`, `user_no` )"
                    + " values('"+log+"', '"+guserno+"')"; 
                  stmt.execute(querys);
               }else{
                   
                   database database = new database();
                Statement stmt = database.getconnect();
                String query = "UPDATE users SET Balance ='"+total+"' WHERE user_id ='"+sessionid+"'";
                stmt.execute(query);
               
                balances.setText("Balance:"+total);
                
                globalbalance = total;
                 bal = total;
                 String log = globalnam+" Deposited "+deps;
                  String querys = "insert into logs(`message`, `user_no` )"
                    + " values('"+log+"', '"+guserno+"')"; 
                  stmt.execute(querys);
               }
            }
        } catch (SQLException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
      this.setVisible(false);
      login x = new login();
     x.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balances;
    private javax.swing.JLabel errs;
    private javax.swing.JLabel greatings;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel limit;
    // End of variables declaration//GEN-END:variables
}
